### ISSUE TITLE
Dependency `fancy_surreal` is missing / relative path

### ISSUE THREAD

**Issue by julianbuettner** [xilefmusics/money-app#29]
When trying to start the backend (`./run.sh bckend`) the following error is printed:

```
Updating crates.io index
error: failed to get `fancy_surreal` as a dependency of package `backend v0.1.0 (/home/julian/test/money-app/backend)`

Caused by:
  failed to load source for dependency `fancy_surreal`

Caused by:
  Unable to update /home/julian/test/fancy_surreal

Caused by:
  failed to read `/home/julian/test/fancy_surreal/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Also, an installation section in the `README.md` would be useful.

**Comment by xilefmusics** [comment]
At the moment the dependencies fancy_surreal and fancy_yew have to be manually resolved and cloned next to the money-app project. Everything is now documented in the usage section of the new README. https://github.com/xilefmusics/money-app
